
[font]
size = 8.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "DejaVu Sans Mono"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
opacity = 0.8

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true

import = ["~/.config/alacritty/themes/tokyo-night.toml"]

[keyboard]
bindings = [
  { key = "Return", mods = "Control", chars = "\u001b[13;5u" }
]
