preload = /home/dfalcon/Pictures/Wallpapers/nord/anime-eye-nord.png
wallpaper = eDP-1,/home/dfalcon/Pictures/Wallpapers/nord/anime-eye-nord.png
wallpaper = DP-1,/home/dfalcon/Pictures/Wallpapers/nord/anime-eye-nord.png
