background {
    monitor     =
    blur_passes = 3
    blur_size   = 7
    brightness  = 0.8
}

input-field {
    monitor  =
    size     = 250, 50
    position = 0, -80
    halign   = center
    valign   = center

    outer_color       = rgb(7aa2f7)
    inner_color       = rgb(24283b)
    font_color        = rgb(c0caf5)
    placeholder_text  = <i>Пароль...</i>
    check_color       = rgb(9ece6a)
    fail_color        = rgb(f7768e)
    fail_text         = <i>Неправильно ($ATTEMPTS)</i>
}

label {
    monitor   =
    text      = cmd[update:1000] echo "$TIME"
    color     = rgba(c0caf5ff)
    font_size = 50
    position  = 0, 100
    halign    = center
    valign    = center
}
