-- Generated by nwg-displays on 2026-08-29 at 11:09:26. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "3072x1920@120.0",
    position = "1920x0",
    scale = 1.6
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0
})
