-- Generated by nwg-displays on 2026-08-19 at 14:27:32. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@59.99",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100.0",
    position = "0x0",
    scale = 1
})
